### ISSUE TITLE
Crashing occasionally, seemingly when balance has been moved away from center by OSX bug.

### ISSUE THREAD

**Issue by mcelligottnick** [jamsinclair/ballast#14]
OSX: 10.14.1 (18B75)
Hardware: MacBook Pro (15-inch, 2018)
Ballast: 1.1.0-beta

Since I started using Ballast I've noticed that every time I've needed it, it has been closed. Upon seeing this happen a few times I started taking more notice of when Ballast was running. 

It seems that Ballast is running most of the time, and does run when I start up. However when the audio balance gets screwed up Ballast will not be there, and from the pattern of seeing this happen I think Ballast may be crashing just as it's trying to reset the balance. 

This happens maybe once every 3-7 days?

After restarting Ballast it will immediately fix the balance and increment the "corrected" counter.

I don't do any OSX app development but happy to give it a go if perhaps you could point me to where in logs or otherwise I might be able to see some errors? It would be hard to reproduce during testing I think since its relatively rare.

**Comment by jamsinclair** [comment]
Thanks @mcelligottnick. I encounter the same problem, but only on one of my MacBooks. I've been meaning debug these crashes further. 

When the app crashes it should save a crash report to the directory: 
`/Users/<user-name>/Library/Logs/DiagnosticReports/`

The crash files will be prefixed with `ballast_`. If you have any of these files, please post the most recent crash report in this issue or a [pastebin](https://pastebin.com/). Should help provide some great context. 

Thanks for raising!

**Comment by mcelligottnick** [comment]
Hey mate [here is the pastebin](https://pastebin.com/bQafBSYw) of my most recent log. Let me know if I can be of further help.

**Comment by chairamisu** [comment]
Hello! I have had a similar problem except Ballast only starts up when I restart my MacBook. I cannot open Ballast from the app itself and I have it set to open with each login through another app. Every time I use a different audio source (eg moving from Spotify to Discord) Ballast disappears from the menu bar with the audio being imbalanced again and I cannot reopen it without restarting.

Here is the [Pastebin](https://pastebin.com/YYpQbqPK) of the most recent crash report if it helps. Otherwise this works beautifully! Thank you so much for dedicating your time to this 😀

**Comment by mcelligottnick** [comment]
hey @jamsinclair any chance you are able to take a look at this, or point me in the right direction to helping solve it?

**Comment by jamsinclair** [comment]
Thanks @mcelligottnick @chairamisu. Finally got around to taking a look. 

I suspect the app was encountering an audio error that I wasn't handling properly. Hopefully fixed in: https://github.com/jamsinclair/ballast/releases/tag/v1.2.0

Let me know if it helps! 😄

**Comment by mcelligottnick** [comment]
@jamsinclair thanks mate, will re-open if the issue persists.

**Comment by mcelligottnick** [comment]
Hey @jamsinclair this issue is still there with the new build. I had two crashes yesterday;

- https://pastebin.com/nWvCiLsL
- https://pastebin.com/yiu1X59E

Let me know if you need anything else.

**Comment by jamsinclair** [comment]
Thanks for that @mcelligottnick! Hmmm I'll investigate further 🤔

**Comment by jamsinclair** [comment]
I just revisited the issue tonight @mcelligottnick. I feel bad for not noticing this sooner, your logs show they crashed using the older version `1.1.0`.

This may have happened due to having both the old and new `.app` files and the launch at login option checked. Try removing all `ballast.app` files from your mac and download the [latest version](https://github.com/jamsinclair/ballast/releases/latest) again 🤞

**Comment by mcelligottnick** [comment]
Cheers mate will try that, and let you know how it goes.
